a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
print ("Equal:",a == b)
print ("Not Equal:", a != b)
print ("Greater than:", a > b)
print ("Less than:", a < b)
print ("Greater than or equal:", a >= b)
print ("Less than or equal:", a <= b)
